apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tp1fgr20t-go
  janus-idp.io/tekton: tp1fgr20t-go
  backstage.io/kubernetes-id: tp1fgr20t-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tp1fgr20t-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
