apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tp1fgr20t-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tp1fgr20t-go 
  name: tp1fgr20t-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tp1fgr20t-go 
